spring:
  application:
    name: netflix-eureka-consumer

server:
  port: 8083

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30  # ???????????????????????30?
    instance-id: consumer1 # ????Eureka??????????
    prefer-ip-address: true # ???Eureka??????ip?????instanceid???????ip
  client:
    registry-fetch-interval-seconds: 30  # ??????????????30?
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka # ??????????
