spring:
  application:
    name: netflix-eureka-server
server:
  port: 8080

# 测试：http://127.0.0.1:8080
eureka:
  instance:
    hostname: 127.0.0.1 # hostname是eureka集群服务器之间的区分
    lease-expiration-duration-in-seconds: 90 #最后一次心跳后，间隔多久认定微服务不可用，默认90
  client:
    register-with-eureka: false # 是否向自身注册：由于该应用为单个注册中心，所以设置为false，代表不向注册中心注册自己
    fetch-registry: false # 是否从自身拉取注册信息。由于单个注册中心，不拉去自身注册信息
  server:
    enable-self-preservation: false # 是否开启eureka自我保护状态